version: 0.2

env:
  git-credential-helper: yes
  variables:
    SENTRY_ORG: opacity
    SENTRY_PROJECT: storage-node
  parameter-store:
    SENTRY_AUTH_TOKEN: /storage-node/SENTRY_AUTH_TOKEN

phases:
  install:
    on-failure: ABORT
    commands:
      - curl -sL https://sentry.io/get-cli/ | bash
  pre_build:
    on-failure: ABORT
    commands:
      - VERSION=`sentry-cli releases propose-version`
      - sentry-cli releases new "$VERSION"
      - git remote remove origin
      - git remote add origin https://github.com/opacity/storage-node.git
      - sentry-cli releases set-commits "$VERSION" --auto --ignore-missing --ignore-empty
      - echo "VERSION=$VERSION" >> .env
      - echo "GO_ENV=$GO_ENV" >> .env
      - echo "IMAGE_TAG=$GO_ENV" >> .env
      - echo "AWS_REGION=$AWS_REGION" >> .env
      - echo "DEBUG=$DEBUG" >> .env
      - echo "ADMIN_USER=$(aws ssm get-parameter --name /storage-node/$GO_ENV/ADMIN_USER --with-decryption --output text --query Parameter.Value)" >> .env
      - echo "ADMIN_PASSWORD=$(aws ssm get-parameter --name /storage-node/$GO_ENV/ADMIN_PASSWORD --with-decryption --output text --query Parameter.Value)" >> .env
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws
      - docker-compose pull
  build:
    on-failure: ABORT
    commands:
      - docker-compose build

  post_build:
    on-failure: ABORT
    commands:
      - docker-compose push
      - sentry-cli releases finalize "$VERSION"
      - sentry-cli releases deploys "$VERSION" new -e $GO_ENV

