version: 0.2

env:
  git-credential-helper: yes
  variables:
    SENTRY_ORG: opacity
    SENTRY_PROJECT: storage-node
  parameter-store:
    SENTRY_AUTH_TOKEN: /storage-node/SENTRY_AUTH_TOKEN

phases:
  install:
    on-failure: ABORT
    commands:
      - curl -sL https://sentry.io/get-cli/ | bash
  build:
    on-failure: ABORT
    commands:
      - SVERSION=`sentry-cli releases propose-version`
      - VERSION="${CODE_PIPELINE_ENV}@${SVERSION}"
      - sentry-cli releases new "$VERSION"
      - sentry-cli releases set-commits "$VERSION" --auto --ignore-missing --ignore-empty
      - echo $VERSION > .version
      - sentry-cli releases finalize "$VERSION"
artifacts:
  files:
    - '**/*'
