version: 0.2

env:
  git-credential-helper: yes
  variables:
    SENTRY_ORG: opacity
    SENTRY_PROJECT: storage-node
  parameter-store:
    SENTRY_AUTH_TOKEN: /storage-node/SENTRY_AUTH_TOKEN

phases:
  install:
    on-failure: ABORT
    commands:
      - curl -sL https://sentry.io/get-cli/ | bash
  build:
    on-failure: ABORT
    commands:
      - VERSION=`sentry-cli releases propose-version`
      - sentry-cli releases new "$VERSION"
      - git remote remove origin
      - git remote add origin https://github.com/opacity/storage-node.git
      - sentry-cli releases set-commits "$VERSION" --auto --ignore-missing --ignore-empty
      - echo "VERSION=\"$VERSION\"" >> .env
      - echo "GO_ENV=\"$GO_ENV\"" >> .env
      - echo "AWS_REGION=\"$AWS_REGION\"" >> .env
      - echo "DEBUG=\"$DEBUG\"" >> .env
      - sentry-cli releases finalize "$VERSION"
      - sentry-cli releases deploys "$VERSION" new -e $GO_ENV
artifacts:
  files:
    - '**/*'
