version: "3"

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -delayTransientStatuses -dbPath /dynamodblocal/data"
    user: root
    image: "amazon/dynamodb-local:latest"
    restart: "always"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./data/dynamodb/test:/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks: 
      - dbnet

  app:
    build: "."
    restart: "always"
    ports:
    - ${APP_PORT:-3000}:3000
    env_file:
      - ".env"
    depends_on:
    - "db"
    - "dynamodb-local"
    volumes:
    - ".:/go/src/github.com/opacity/storage-node"
    - "./data/badger/prod:/var/lib/badger/prod"
    - "./data/badger/test:/var/lib/badger/test"
    working_dir: "/go/src/github.com/opacity/storage-node"
    command: >
      bash -c "
        echo waiting for db...;
        while ! nc -z db 3306;
        do
          sleep 0.5;
          free -m;
        done;
        while ! nc -z dynamodb-local 8000;
        do
          sleep 0.5;
          free -m;
        done;
        echo ${DEBUG}
        go get github.com/codegangsta/gin
        if [ -z ${DEBUG} ]; then
          echo \"Starting Storage node in PROD mode\";
          go build -o ./bin/storage-node && chmod +x ./bin/storage-node;
          ./bin/storage-node;
        else
          echo \"Starting Storage node in DEV mode\";
          gin run main.go
        fi
      "
    networks:
      - dbnet

  db:
    container_name: mysql
    image: mysql:5.7
    restart: "always"
    command: --sql_mode=''
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "33060:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    networks:
      - dbnet

# In order for each service to connect to each other, They need to be on the same
# network and use name like "app", "db", "prometheus" for reference. Ex: "db:3306", "app:3000".
networks:
  dbnet:
    driver: bridge


